---
abstract: 'Filter a string to meet URI requirements'
author:
  - 'Moritz Onken <onken@houseofdesign.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Template-Plugin-Text-Filter-URI
no_index:
  directory:
    - t
    - inc
requires:
  Template: 0
  Test::More: 0
  Text::Filter::URI: 0
version: 0.03
