--- #YAML:1.0
name:               Template-Plugin-Text-Filter-URI
version:            0.02
abstract:           Filter a string to meet URI requirements
author:
    - Moritz Onken <onken@houseofdesign.de>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Template:           0
    Test::More:         0
    Text::Filter::URI:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
