# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-Text-Filter-URI
version:      0.01
version_from: lib/Template/Plugin/Text/Filter/URI.pm
installdirs:  site
requires:
    Template:                      0
    Test::More:                    0
    Text::Filter::URI:             0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
